### ISSUE TITLE
Use default theme

### ISSUE THREAD

**Issue by DirtyF** [netlify-templates/jekyll-base#2]
Since the original commit of this repo, jekyll added support for [gem-based-themes](https://jekyllrb.com/docs/themes/#understanding-gem-based-themes) (the files used for the theme are stored in the Ruby gem not in the source directory). 

Since there is no README, I'm not sure how this repo is used by Netlify, but I was wondering if you'd be interested in a PR that makes use of jekyll's default theme instead of having to version all files in this repo.

It will allow easier theme upgrade through bundle for users.

**Comment by DirtyF** [comment]
Closing as this hasn't raise any interest by the maintainers.

**Comment by erquhart** [comment]
Yeah we're leaning on the community quite a bit for the lesser used themes. The Jekyll Netlify CMS theme has had a fair amount of activity, and it uses Minima via gem: https://github.com/netlify-templates/jekyll-netlify-cms
